import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import HeaderWrapper from "@/components/HeaderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <HeaderWrapper isAdminPage={false} />
        <main className="min-h-screen">{children}</main>
        <Toaster richColors position="top-right" />
        <footer className="bg-black text-white">footer</footer>
      </body>
    </html>
  );
}
