import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "sonner";

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >

<Header isAdminPage={false}/>
        
        <main className="min-h-screen my-20">
        {children}
        </main>
        <Toaster richColors />
        <footer className="bg-black text-white">footer</footer>
      </body>
    </html>
  );
}
